---
- name: Nvidia Container Toolkit Repo
  ansible.builtin.shell:
    cmd: curl --output  /etc/yum.repos.d/nvidia-container-toolkit.repo https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
- name: K8 Repo
  ansible.builtin.copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
- name: docker repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
- name: dnf update
  ansible.builtin.shell:
    cmd: dnf update -y
- name: Install docker, containerd, nvidia container toolkit
  ansible.builtin.shell:
    cmd: dnf install docker-ce docker-ce-cli containerd.io nvidia-container-toolkit -y
- name: Docker Daemon Config
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  become: yes
- name: Containerd Configuration
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/containerd/config.toml
  become: yes
  notify:
    - Restart containerd
- name: Turn Swapoff for K8
  ansible.builtin.shell:
    cmd: swapoff -a
- name: Remove swap file for K8
  ansible.builtin.shell:
    cmd: rm -f /swapfile
- name: Install kubeadm kubelet
  ansible.builtin.shell:
    cmd: dnf install kubeadm kubelet --disableexcludes=kubernetes -y
- name: Start Docker
  ansible.builtin.shell:
    cmd: systemctl start docker
- name: Enable Kubelet Service
  ansible.builtin.shell:
    cmd: systemctl enable kubelet.service
- name: Install iputils
  ansible.builtin.shell:
    cmd: dnf install iputils